# Generated by Django 5.2 on 2025-05-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
